# sonar-project.properties
sonar.projectKey=UI5-E2E-Tests
sonar.projectName=UI5 E2E Tests (WDI5 + OPA5 + UiVeri5)
sonar.projectVersion=1.0
sonar.sources=webapp
sonar.tests=webapp/test
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/reports/**,**/*.min.js,webapp/test/**,webapp/Component.js
sonar.test.inclusions=webapp/test/**/*.test.js,webapp/test/**/*.spec.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.junit.reportPaths=reports/junit/wdi5,reports/junit/opa5,reports/junit/uiveri5
sonar.testExecutionReportPaths=reports/sonar-test-execution.xml